apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minikube-victorialogs
  namespace: argocd
spec:
  destination:
    namespace: vm
    server: https://kubernetes.default.svc
  project: observability
  source:
    path: overlays/minikube
    repoURL: https://github.com/Vail-X/project-victorialogs
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
